version: '3.6'

services:

  # Subject line scoring API
  api:
    image: subject-line-service:latest
    build:
      context: ./
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/local/flask/app
      - ./up.sh:/usr/local/flask/up.sh
      - ./gunicorn.py:/usr/local/flask/gunicorn.py
